### ISSUE TITLE
bug squashing

### ISSUE THREAD

**Issue by jamac-dumas** [James-Dumas/cryptscript#6]
run cryptscript code to find bugs
try to write stupid ass code that breaks stuff

things to look for:
errors being displayed incorrectly/when they shouldn't be, or errors not being displayed when they should be
incorrect outputs from math or logic computations
mistakes parsing loops, functions, loops in functions, loops in loops, loops in loops in loops, etc.
mistakes parsing loop conditions or function arguments
any exceptions thrown by the debugger, obviously

if you find anything, post your code and what problem it caused

note: you can run a script file by passing the file name as an argument or running `utilize "path/to/script"` in the interpreter

**Comment by icorbrey** [comment]
@JamesDumas so this is dead, can you close the issue? Thanks!

**Comment by LvInSaNevL** [comment]
@icorbrey Sorry but this project will never die and as such any and all open issue should stay open

**Comment by jamac-dumas** [comment]
it will always live on in our hearts
